name: Deploy Api to Railway

on:
  push:
    branches:
      - main
    paths:
      - "api/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: modernstack-api
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
        - uses: actions/checkout@v3
        - run: railway up --service=${{ env.SVC_ID }}