name: Deploy Api to Railway

on:
  push:
    branches:
      - main
    paths:
      - "api/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: bervProject/railway-deploy@main
        env:
            RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN}}
        with:
            service: "modernstack-api"